name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1 # 구체적인 최신 버전으로 변경
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GitHub Actions에서 제공하는 기본 토큰
          projectId: emoticare-n # Firebase 프로젝트 ID (콜론 뒤 공백 확인)
          channelId: live # 라이브 채널에 배포
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}' # Firebase 토큰을 환경 변수로 설정
          FIREBASE_CLI_PREVIEWS: hostingchannels # 필요한 경우 채널 기능 활성화
