# 서비스 계정 방식을 사용합니다.
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0 # 액션 버전은 v0 유지
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GitHub Actions에서 제공하는 기본 토큰
          firebaseServiceAccount: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' # 변경된 시크릿 이름 사용
          projectId: emoticare-n
          channelId: live
