name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GitHub Actions에서 제공하는 기본 토큰
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMOTICARE_N }}' # 서비스 계정 JSON 키 내용
          projectId: emoticare-n # Firebase 프로젝트 ID (콜론 뒤 공백 확인)
          channelId: live # 라이브 채널에 배포
        # env: # FIREBASE_TOKEN 방식은 이제 사용하지 않습니다.
          # FIREBASE_TOKEN: '${{ secrets.FIREBASE_TOKEN }}'
          # FIREBASE_CLI_PREVIEWS: hostingchannels
